### PR TITLE
41 update get post and put endpoints for donateditem with full program and donor details

### LINKED ISSUE #41: Update GET, POST, and PUT Endpoints for /donatedItem with Full Program and Donor Details
Update the GET, POST, and PUT endpoints for managing Donated Items to handle new relationships involving Program and Donor entities. Previously, Program and Donor Email were stored directly as strings, but they have now been replaced by foreign keys to the Program and Donor tables. The endpoints need to be updated to ensure the full Program and Donor details are properly fetched, stored, and updated.

**Requirements:**

- [ ] **GET /donatedItem Endpoint:**

- Update the GET /donatedItem endpoint to include full Program and Donor details in the response.
- Previously, Program and Donor Email were directly stored and returned. Now that these columns have been replaced with foreign keys (programId and donorId):
- Use the foreign keys to fetch Program and Donor details from their respective tables.
- Return full Program details such as name, description, and any other fields required.
- Return full Donor details such as name, email, contact number, and other relevant information.
- Include these details in the response for each Donated Item alongside fields like itemType, currentStatus, dateDonated, etc.

- [ ] **POST /donatedItem Endpoint:**

- Update the POST /donatedItem endpoint to handle the new foreign key relationships.
- Previously, Program name and Donor email were stored directly as they were received from the request.
- Now, the process should be updated as follows:
- Program Validation: Validate the received Program name against the Program table and retrieve its Program ID.
- Donor Validation: Validate the received Donor email against the Donor table and retrieve its Donor ID.
- Store the Program ID and Donor ID instead of the original strings (programName and donorEmail).
- If the Program or Donor does not exist, return an appropriate error response.

- [ ] **PUT /donatedItem/details/{id} Endpoint:**

- Update the PUT /donatedItem/details/{id} endpoint to allow updates to non-status fields for a specific Donated Item.
- Fields to be updated include:
- itemType, program, donorEmail, and dateDonated.
- When updating Program and Donor fields:
- Validate the new Program name and Donor email against their respective tables.
- Update the foreign keys (programId and donorId) to reflect the new associations when they are changed.
- Ensure that other fields (itemType, dateDonated) are also updated correctly.

- [ ] **Detailed Requirements:**

**Validation and Error Handling:**

- If the Program or Donor details provided do not exist in the database, return a 400 Bad Request with an appropriate error message.
- Ensure that foreign keys are only updated if the provided Program or Donor is valid.
- Handle exceptions such as database errors and provide user-friendly messages for failed operations.

**Database Query Optimization:**

- Optimize queries to fetch Program and Donor details using joins where possible, especially for the GET endpoint to minimize multiple database calls and improve efficiency.
- Ensure that the queries include all required fields from both the Program and Donor tables.

- [ ] **Testing:**

Write unit tests for each endpoint to verify the following scenarios:
**GET /donatedItem:**

- Ensure that full Program details and full Donor details are included in the response.
- Test response correctness for both existing and non-existent Program and Donor references.

**POST /donatedItem:**

- Validate that Program name and Donor email are checked against the database before storing their IDs.
- Test error handling when the provided Program or Donor does not exist.

**PUT /donatedItem/details/{id}:**

- Ensure updates to itemType, program, donorEmail, and dateDonated correctly modify the relevant foreign key values.
- Test scenarios where updates are made with invalid Program or Donor values, ensuring appropriate error responses.

### PR DESCRIPTION
**Pull request by saikiran0405**
**Fixes #41 **

### What was changed?

- Updated the GET, POST, and PUT endpoints for managing Donated Items to handle new relationships involving Program and Donor entities.
- Written unit tests for each endpoint according to the requirement.

### Why was it changed?

-  Previously, Program and Donor Email were stored directly as strings, but they have now been replaced by foreign keys to the Program and Donor tables. The endpoints need to be updated to ensure the full Program and Donor details are properly fetched, stored, and updated

### How was it changed?

- Previously, Program and Donor Email were directly stored and returned. Now that these columns have been replaced with foreign keys (programId and donorId):
- Previously, Program name and Donor email were stored directly as they were received from the request.

Now, the process should be updated by using validations:

Program Validation: Validated the received Program name against the Program table and retrieve its Program ID.

Donor Validation: Validated the received Donor email against the Donor table and retrieve its Donor ID.

### CODE REVIEW

File: server/src/routes/donatedItemRoutes.ts [hunk 1]
```diff
@@ -21,8 +42,21 @@ router.post('/', donatedItemValidator, async (req: Request, res: Response) => {
                 // dateDonated: new Date(dateDonated).setUTCHours(0,0,0,0), // Set time to 00:00:00 UTC
             },
         });
-        console.log('New donated item created:', newItem);
-        res.status(201).json(newItem);
+        const newStatus = await prisma.donatedItemStatus.create({
+            //where: { id: Number(req.params.id) },
```
Comment (Anjali0407-git) [inline server/src/routes/donatedItemRoutes.ts:46]: remove unnecessary comments

File: server/src/__tests__/donatedItem.test.ts [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+
+describe('DonatedItem API Tests', () => {
+    beforeEach(() => {
+        jest.clearAllMocks();
+    });
+
+    // Test POST /donatedItem
+    it('validates Program name and Donor email before creating a donated item', async () => {
+        mockPrismaClient.program.findUnique.mockResolvedValue({ id: 1, name: 'Valid Program', description: 'Valid', startDate:'2024-10-04', aimAndCause:'recycle' });
+        const newDonor = {
```
Comment (Anjali0407-git) [inline server/src/__tests__/donatedItem.test.ts:18]: Can you move all the mock data across this file into seperate file/directory? It will facilitate us to reuse that data in many test files.

File: server/src/routes/donatedItemRoutes.ts [hunk 3]
```diff
@@ -8,7 +8,28 @@ const router = Router();
...
+
+        // Validate programId
+        const programExists = await prisma.program.findUnique({
+            where: { id: req.body.programId }
+        });
+
+        
+        if (!programExists) {
+            return res.status(400).json({ error: "Program ID is not valid or does not exist." });
+        }
```
Comment (Anjali0407-git) [inline server/src/routes/donatedItemRoutes.ts:33]: I have seen the donor and program validation in both POST and PUT requests. Can we consolidate it so that there will be no duplicate code?

**Review by truffer11 — CHANGES_REQUESTED** [review]
Once again, really solid work! Not too many notes for this sprint, just a few comments that may have been repetitive code. But those are simple changes/checks. Keep up the good work!

File: server/src/__mocks__/mockUpdateData.ts [hunk 4]
```diff
@@ -0,0 +1,7 @@
+export const updateData = {
+    itemType: 'Updated Book',
+    currentStatus: 'Received',
+    programId: 1,
+    donorId: 1,
+    dateDonated: new Date().toISOString()
+};
```
Comment (Anjali0407-git) [inline server/src/__mocks__/mockUpdateData.ts:7]: what data is this? can we move this to other relevant mock data files?

File: server/src/__tests__/donatedItem.test.ts [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+
+describe('DonatedItem API Tests', () => {
+    beforeEach(() => {
+        jest.clearAllMocks();
+        // Setup mock responses
+        mockPrismaClient.program.findUnique.mockResolvedValue(newProgram);
+        mockPrismaClient.donor.findUnique.mockResolvedValue(newDonor);
+        mockPrismaClient.donatedItem.create.mockResolvedValue({ id: 1, ...newItem });
+        mockPrismaClient.donatedItem.update.mockResolvedValue({ id: 1, ...updateData });
+    });
```
Comment (Anjali0407-git) [inline server/src/__tests__/donatedItem.test.ts:22]: Nice! Keeping the required mock resolved values for prisma at one place seems more clear

**Review by Anjali0407-git — CHANGES_REQUESTED** [review]

**Review by Anjali0407-git — APPROVED** [review]

File: server/src/__tests__/donatedItem.test.ts [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+
+    // Test POST /donatedItem
+    it('validates Program name and Donor email before creating a donated item', async () => {
+        const response = await request(app).post('/donatedItem').send(newItem);
+        expect(response.status).toBe(201);
+        expect(mockPrismaClient.donatedItem.create).toHaveBeenCalled();
+    
+    });
+
+    it('handles errors when the provided Program or Donor does not exist', async () => {
```
[the remark this answers is not in the document]
Comment (saikiran0405) [reply server/src/__tests__/donatedItem.test.ts:31]: @truffer11 It wouldn't check in the real or actual database; it will use mock prisma client and you can see at [this line](https://github.com/oss-slu/material-donor-mutual-assist/pull/49/files#diff-cacffbaf92d007aa8421f8e53bdff31e2a3a00d9553542b6b548764b82a7d823R35) that it resolves to value `null`  and it always resolves to null values irrespective of the size of database
